name: CI and Release
on:
  push:
    branches:
      - main
    # Trigger on version tags
    tags:
      - "v*"
  pull_request:
  merge_group:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      GO_VERSION: "1.22"

  test:
    uses: ./.github/workflows/test.yml
    with:
      GO_VERSION: "1.22"

  # Make a release if this is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v4
      - name: Version Release
        uses: rollkit/.github/.github/actions/version-release@v0.3.0
        with:
          github-token: ${{secrets.PAT_FOR_DOCKER_TRIGGER}}
          version-bump: ${{inputs.version}}
